# Generated by Django 2.2.1 on 2019-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='dismissal_kind',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='fielder',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='player_dismissed',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
